### ISSUE TITLE
Suggestion to replace the UoE art collection dataset (w6d2)

### ISSUE THREAD

**Issue by ZenoMK** [ids-s1-20/lectures#5]
Since there are five lectures and one lab on datasets relating to art, it might be interesting to scrape another website for this lecture. One idea for a suitable replacement would be wikipedia lists such as this one: https://en.wikipedia.org/wiki/List_of_countries_by_past_and_projected_GDP_(nominal)

**Comment by mine-cetinkaya-rundel** [comment]
I think it would be a good idea to replace the Paris Paintings dataset with another modeling dataset, where the relationships are a bit more obvious. Want to try out a dataset like the one you suggest to see if simple relationship appear better?

**Comment by ZenoMK** [comment]
Yes, I'll try out the oceanographic dataset and will get back to you with results until tomorrow!

**Comment by ZenoMK** [comment]
Hi Mine, I fitted a couple of models that are comparable to the ones used in the lecture.
I think the house price dataset would work well in a lecture, mainly because there are some clear linear relationships that might be more intuitive for students to understand (such as the relationship of living space and price). 
If you want to look at the analysis, here it is: 
`new-data/house-prices/House-Prices-Modelling.md`

If you would like me to recreate all plots and analyses from the 4 Paris paintings, please let me know.

**Comment by mine-cetinkaya-rundel** [comment]
The Ames, Iowa housing dataset is a well known one, it's in quite a few textbooks as well. Another concern I have is that it's old -- but we might be able to find a newer housing dataset which would be a nice change from the Ames, Iowa one. Let's say this is a good backup dataset, but I'd like to keep looking.

**Comment by ZenoMK** [comment]
Ok, I'll keep looking!

**Comment by ZenoMK** [comment]
I have found two datasets, one related to sales in King County, OR, (2015)  the other one to real estate listings in Argentina (2016). Both contain variables that are comparable to the ones I used for the Ames dataset.
I would prepare presentations like the one above until tomorrow before our call, unless you decide those are not recent enough? In that case, I'll continue datahunting.

**Comment by ZenoMK** [comment]
Links in case you want to have a look: 
[https://www.kaggle.com/harlfoxem/housesalesprediction](url)
[https://www.kaggle.com/harlfoxem/housesalesprediction](url)

**Comment by mine-cetinkaya-rundel** [comment]
I would be fine with either of these. So give it a try and see which one works better? Feel free to start with whichever one you think is more interesting. 

And note that you'll probably need to log transform the outcome variable (price).

Adding a R Markdown file with similar code to what was used in the slides for Paris Paintings would be sufficient. Feel free to leave the prose in bullet points, just a rough sketch showing "this should work" is fine for me. Thank you!

**Comment by ZenoMK** [comment]
I'm on it right now, you will get it before we talk!

**Comment by ZenoMK** [comment]
Hi Mine, 
The Argentina dataset has some significant flaws, so I believe the King County dataset would be better suited for the task. I put a document into the King-County folder for you to review if you like.

**Comment by mine-cetinkaya-rundel** [comment]
King county analysis is looking good, thank you! I'll replace the paris paintings with that one, and bring paris paintings in an earlier (data wrangling) lesson.
