### ISSUE TITLE
Suggestion to replace paris paintings dataset (w7d1)

### ISSUE THREAD

**Issue by ZenoMK** [ids-s1-20/lectures#6]
While I like the art dataset, it might be interesting to add more variety to the lectures on modelling, such as using different datasets for predicting continuous or categorical data. I will add the dataset proposals to the folder.

**Comment by mine-cetinkaya-rundel** [comment]
See #5. Agreed! I think I prefer to replace the paris pantings instead of UoE art.

**Comment by mine-cetinkaya-rundel** [comment]
Addressed in #5, closing this issue.
